[package]
name = "statechannels-native-utils-wasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
statechannels-native-utils-common = { path = "../common" }